name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      deployments: write
    environment:
      name: production
      url: https://images.csssr.com

    steps:
      - name: Download CSSSR actions
        uses: actions/checkout@v2
        with:
          repository: CSSSR/actions
          ssh-key: ${{ secrets.DOWNLOAD_ACTIONS_SSH_KEY }}
          path: actions

      - uses: actions/checkout@v4
        with:
          path: csssr_images

      - name: Install dependencies
        working-directory: csssr_images
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: csssr_images
        run: yarn run build-example
        env:
          HOST: http://master.csssr-images.csssr.cloud
          IMGPROXY_HOST: https://images.csssr.com

      - name: Import secrets
        id: secrets
        uses: ./actions/get-aws-s3-upload-creds/v1beta1
        with:
          VAULT_JWT_KEY: ${{secrets.VAULT_JWT_KEY}}

      - name: Deploy
        uses: ./actions/deploy-static-site/v1beta1
        with:
          auth: 'aws:${{steps.secrets.outputs.AWS_ACCESS_KEY_ID}}:${{steps.secrets.outputs.AWS_SECRET_ACCESS_KEY}}:${{steps.secrets.outputs.AWS_SESSION_TOKEN}}'
          token: ${{ secrets.GITHUB_TOKEN }}
          site-type: mpa
          project-id: csssr-images
          files: ./csssr_images/example
          no-previous-files: 'true'
